version: "3.8"

services:
  document_extractor:
    build: .
    container_name: doc_extraction
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/app
    ports:
      - "3008:3008" 
    command: ["python", "api.py"]
